DISTRO = "gateway-os"
DISTRO_NAME = "GatewayOS (Robust Multi-Protocol IoT Gateway OS)"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "scarthgap-based"
MAINTAINER = "Daniel Kampert <kontakt@daniel-kampert.de>"

require conf/distro/poky.conf

INIT_MANAGER = "systemd"

DISTRO_FEATURES:append = " pam virtualization wifi bluetooth overlayfs"
DISTRO_FEATURES:remove = "x11 wayland 3g alsa opengl vulkan"

PACKAGECONFIG:append:pn-systemd = " networkd resolved"
VIRTUAL-RUNTIME_net_manager = "systemd"
